export const allCourses = [
    {
        id: 1,
        img: "https://i.ibb.co/V3ZZfSp/course-1.jpg",
        title: "The Python Mega Course: Build 10 Real World Applications",
        desc: "Go from zero to hero in Python in weeks! Learn Python the easy way by building real-life Python programs!",
        ratings: 4.6,
        creator: "Ardit Sulce",
        price: 189.99,
    },
    {
        id: 2,
        img: "https://i.ibb.co/DgbH5cF/course-2.jpg",
        title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
        desc: "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!",
        ratings: 4.7,
        creator: "Maximilian",
        price: 79.99,
    },
    {
        id: 3,
        img: "https://i.ibb.co/p0GBDnW/course-3.jpg",
        title: "Learn Python Programming Masterclass",
        desc: "This Python For Beginners Course Teaches You The Python Language Fast. Includes Python Online Training With Python 3.",
        ratings: 4.5,
        creator: "Tim Buchalka",
        price: 59.99,
    },
    {
        id: 4,
        img: "https://i.ibb.co/NZZ1fB9/course-4.jpg",
        title: "Java Programming Masterclass covering Java 11 & Java 17",
        desc: "Learn Java In This Course And Become a Computer Programmer. Obtain valuable Core Java Skills And Java Certification.",
        ratings: 4.6,
        creator: "ATim Buchalka",
        price: 129.99,
    },
    {
        id: 5,
        img: "https://i.ibb.co/RCT7mjQ/course-5.jpg",
        title: "2021 Complete Python Bootcamp From Zero to Hero in Python",
        desc: "Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games.",
        ratings: 4.6,
        creator: "Jose Portilla",
        price: 13.99,
    },
    {
        id: 6,
        img: "https://i.ibb.co/SnZZYJb/course-6.jpg",
        title: "C# Basics for Beginners: Learn C# Fundamentals by Coding",
        desc: "Master C# fundamentals in 6 hours - The most popular course with 50,000+ students, packed with tips and exercises!",
        ratings: 4.5,
        creator: "Mosh Hamedani",
        price: 89.99,
    },
    {
        id: 7,
        img: "https://i.ibb.co/5GvrC8T/course-7.jpg",
        title: "Automate the Boring Stuff with Python Programming",
        desc: "A practical programming course for office workers, academics, and administrators who want to improve their productivity.",
        ratings: 4.6,
        creator: "Al Sweigart",
        price: 99.99,
    },
    {
        id: 8,
        img: "https://i.ibb.co/HGvPYdx/course-8.jpg",
        title: "Beginning C++ Programming - From Beginner to Beyond",
        desc: "Obtain Modern C++ Object-Oriented Programming (OOP) and STL skills. C++14 and C++17 covered. C++20 info see below.",
        ratings: 4.6,
        creator: "Tim Buchalka",
        price: 80.99,
    },
    {
        id: 9,
        img: "https://i.ibb.co/KxZws3Y/course-9.jpg",
        title: "Spring & Hibernate for Beginners (includes Spring Boot)",
        desc: "Spring 5: Learn Spring 5 Core, AOP, Spring MVC, Spring Security, Spring REST, Spring Boot 2, Thymeleaf, JPA & Hibernate.",
        ratings: 4.6,
        creator: "Chad Darby",
        price: 129.99,
    },
    {
        id: 10,
        img: "https://i.ibb.co/yV83GMs/course-10.jpg",
        title: "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
        desc: "Master Node JS & Deno.js, build REST APIs with Node.js, GraphQL APIs, Authentication, use MongoDB, SQL & much more!",
        ratings: 4.7,
        creator: "Maximilian",
        price: 89.99,
    },
];
